"""align database schema with current models

Revision ID: 098885063789
Revises: 353ca8ea7e28
Create Date: 2026-08-14 14:07:53.967491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098885063789'
down_revision: Union[str, Sequence[str], None] = '353ca8ea7e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliances_id'), table_name='compliances')
    op.drop_table('compliances')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_contract_versions_id'), 'contract_versions', ['id'], unique=False)
    op.alter_column('contracts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contracts', 'contract_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contracts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_contracts_title'), table_name='contracts')
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.drop_column('contracts', 'party_name')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('obligations', sa.Column('assigned_to', sa.Integer(), nullable=False))
    op.add_column('obligations', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('obligations', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'obligations', 'users', ['assigned_to'], ['id'])
    op.create_index(op.f('ix_renewals_id'), 'renewals', ['id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_renewals_id'), table_name='renewals')
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.alter_column('obligations', 'contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('obligations', 'status')
    op.drop_column('obligations', 'assigned_to')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.add_column('contracts', sa.Column('party_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.create_index(op.f('ix_contracts_title'), 'contracts', ['title'], unique=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contracts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contracts', 'contract_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contracts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_contract_versions_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey'))
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('compliances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proof', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('compliances_obligation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('compliances_pkey'))
    )
    op.create_index(op.f('ix_compliances_id'), 'compliances', ['id'], unique=False)
    # ### end Alembic commands ###
