"""message

Revision ID: 7b7a2bdbef26
Revises: ad11532e46ba
Create Date: 2026-08-12 17:21:05.438055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7a2bdbef26'
down_revision: Union[str, Sequence[str], None] = 'ad11532e46ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliances_id'), table_name='compliances')
    op.drop_table('compliances')
    op.drop_index(op.f('ix_obligations_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_title'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey')),
    sa.UniqueConstraint('email', name=op.f('employees_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('contracts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('party_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contracts_pkey'))
    )
    op.create_index(op.f('ix_contracts_title'), 'contracts', ['title'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('obligations_contract_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('obligations_pkey'))
    )
    op.create_index(op.f('ix_obligations_id'), 'obligations', ['id'], unique=False)
    op.create_table('compliances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('obligation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proof', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('compliances_obligation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('compliances_pkey'))
    )
    op.create_index(op.f('ix_compliances_id'), 'compliances', ['id'], unique=False)
    # ### end Alembic commands ###
