"""add contract repository fields

Revision ID: cc61b70c7370
Revises: 098885063789
Create Date: 2026-08-16 11:23:16.794305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc61b70c7370'
down_revision: Union[str, Sequence[str], None] = '098885063789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""

    # Add new columns as nullable first
    op.add_column(
        'contracts',
        sa.Column(
            'category',
            sa.String(length=100),
            nullable=True
        )
    )

    op.add_column(
        'contracts',
        sa.Column(
            'description',
            sa.String(length=1000),
            nullable=True
        )
    )

    op.add_column(
        'contracts',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'contracts',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True
        )
    )

    # Give existing contracts default values
    op.execute(
        """
        UPDATE contracts
        SET
            category = COALESCE(category, 'Vendor Contract'),
            created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
            updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP)
        """
    )

    # Make required fields NOT NULL
    op.alter_column(
        'contracts',
        'category',
        existing_type=sa.String(length=100),
        nullable=False
    )

    op.alter_column(
        'contracts',
        'created_at',
        existing_type=sa.DateTime(),
        nullable=False
    )

    op.alter_column(
        'contracts',
        'updated_at',
        existing_type=sa.DateTime(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'description')
    op.drop_column('contracts', 'category')
    # ### end Alembic commands ###
